### ISSUE TITLE
easeInOutBack: on long animations (e.g. 10 seconds with 16ms step) 1.525^n overflows to NaN

### ISSUE THREAD

**Issue by leok7v** [danro/jquery-easing#5]
on long animations (e.g. 10 seconds with 16ms step) 1.525^n overflows to NaN
in:
easeInOutBack: function (x, t, b, c, d, s) {
        if (s == undefined) s = 1.70158; 
        if ((t/=d/2) < 1) return c/2_(t_t_(((s_=(1.525))+1)_t - s)) + b;
        return c/2_((t-=2)_t_(((s_=(1.525))+1)_t + s) + 2) + b;
}

there is a simple workaround but I wonder if it should be capped?
May be I am reading it wrong.

**Comment by danro** [comment]
Interesting. Can you provide an example that shows when this function would output NaN? 

Something using http://jsfiddle.net/ or http://jsbin.com/ would be great.

**Comment by leok7v** [comment]
Close it. Me "Cloister the Stupid". I was porting to Java (android) and missed ", s)" in parameters - which made it statefull instead of stateless.

**Comment by danro** [comment]
Hah! np, glad to be of some help.
